# Generated by Django 5.0.1 on 2024-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_goal_due_date_alter_saving_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Miscellaneous', 'Miscellaneous'), ('Income', 'Income')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses')], max_length=10),
        ),
    ]
